### ISSUE TITLE
Order of merging

### ISSUE THREAD

**Issue by birdsarah** [avian2/jsonmerge#18]
Hi @avian2, this is a question, as it's been a while since I used jsonmerge. What order does jsonmerge use to merge the documents. Obviously with versioning, some fields are more recent than others, how do we know what the latest is?

**Comment by avian2** [comment]
jsonmerge itself doesn't define an order. You're always merging just two documents: base and head

```
new_base = merge(base, head)
```

```base``` is usually considered older than ```head``` (i.e. containing all merged data up to ```head```). But it all depends on what the chosen merge strategy does.

**Comment by birdsarah** [comment]
Thank you!
