### ISSUE TITLE
Json name/value pairs with forward slash

### ISSUE THREAD

**Issue by chseeling** [avian2/jsonmerge#22]
I used version jsonmerge-1.1.0 with name values pairs like {test: {"MDT_c/kw/day": 0}}
but in current version  a schema error is raised. It appears somethings has changed on how forward slashes are used or interpreted when there are nested objects.

**Comment by avian2** [comment]
Thanks for your bug report. Please provide a minimal, self contained script that raises the schema error you mention and I will look into it.

**Comment by chseeling** [comment]
The code below will produce the error
jsonschema.exceptions.RefResolutionError: Unresolvable JSON pointer: u'tariff/summer/MDT_c/kw/day'
 
```
from jsonmerge import merge

bf = [{"code":'N'}]
tf = [{"code":'M',"tariff":{"summer": {"MDT_c/kw/day": 0}}}]

config = merge(bf[0],tf[0])
print config
```
