### ISSUE TITLE
How do I use `"mergeStrategy": "append"` by default?

### ISSUE THREAD

**Issue by ahuff44** [avian2/jsonmerge#28]
I want the following assertion to pass:

```python
schema = ???
base = None
base = jsonmerge.merge(base, {"a": ["1"], "b": 3}, schema)
base = jsonmerge.merge(base, {"a": ["2"], "b": 4}, schema)

assert base == {"a": ["1", "2"], b: 4}
```

I know that this is possible with 
```python
schema = {
  'properties': {
    'a': {'mergeStrategy': 'append'},
    'b': {'mergeStrategy': 'overwrite'}
  }
}
```
but in my case, I trying to write a general system where the array key isn't necessarily a top-level key named "a"; I want to merge any and all arrays using `"append"` instead of `"overwrite"`.

Is this possible somehow? Ideally I would be able to set `schema` like so: (this obviously does not currently work)
```python
schema = {
  "mergeStrategy": {
    "typeMatch": {
      "object": "objectMerge",
      "array": "append",
      "default": "overwrite"
    }
  }
} 
```

It seems like the best route would be to create a custom merge strategy, but I'm hoping there's an easier solution that I've overlooked

**Comment by avian2** [comment]
Theoretically, what you want could be done with a schema like this:

```json
schema = {
	"oneOf": [
		{
			"type": "array",
			"mergeStrategy": "append"
		},
		{
			"type": "object",
			"additionalProperties": {
				"$ref": "#"
			}
		},
		{
			"type": "string"
		},
		{
			"type": "number"
		},
	]
}
```

This seems to work correctly for validation with current `jsonschema` (even though self-referential schemas are technically [undefined behavior](http://json-schema.org/latest/json-schema-core.html#rfc.section.7)). Unfortunately, `oneOf`keyword is not currently supported at all in `jsonmerge`, so this does not work for merging right now.

I'll look into implementing a basic support for `oneOf` that will work with the schema above. It should be relatively straightforward compared to `anyOf` and `allOf`.

For a quick-and-dirty fix, modify the `WalkInstance.default_strategy` method. I don't think you can achieve what you want with a custom merge strategy.

**Comment by avian2** [comment]
The `oneOf` recipe mentioned above should now work with `jsonmerge` from the master branch.
