### ISSUE TITLE
Add the possibility to disable logging

### ISSUE THREAD

**Issue by ytupychak** [avian2/jsonmerge#35]
I'm getting a couple hundreds of lines like : 

```
__init__.py:46>DEBUG - descend:     schema #
__init__.py:71>DEBUG - descend:     invoke strategy overwrite
```
while doing one of multiple json merging.

Could you, please remove logger from `__init__.py` or make possible to turn it off from outer code.

**Comment by avian2** [comment]
Hi

This is a problem with how your application sets up the Python `logging` module, not jsonschema. It is already possible to decrease logging verbosity or turn off logging all together. Please see documentation here: https://docs.python.org/3/library/logging.html
