### ISSUE TITLE
Merge fails if head has non-ascii key

### ISSUE THREAD

**Issue by Jenna3715** [avian2/jsonmerge#36]
`merge` throws "UnicodeEncodeError" a if the head has a key that contains a non-ascii character

For example, the following code gives the error `"UnicodeEncodeError: 'ascii' codec can't encode character u'\u20b9' in position 0: ordinal not in range(128)"`:
```python
from jsonmerge import merge
from pprint import pprint
base = {
    u'\u20AC': 'euro'
}
head = {
    u'\u20b9': 'indian rupee'
}
result = merge(base, head)
pprint(result)
```

**Comment by avian2** [comment]
Should be fixed now. Thanks for reporting.
