### ISSUE TITLE
oneOf/anyOf of required incorrectly treated as branch

### ISSUE THREAD

**Issue by mrehder** [avian2/jsonmerge#45]
The below JSON Schema construct is purely about enforcement and not structure.
This implements a variant schema enforcement (in the below it says that either A&B must be present or A&C must be present).
This should be ignored for descent and not generate an error.

{ "type" : "object",
                    "anyOf" : 
                    [  { "required" : 
                        [ "A", "B" ] },
                      { "required" : 
                        [ "A", "C" ] } ],

**Comment by avian2** [comment]
Hi. Can you please post a complete code example (with the head and base objects) that generates the error you mention? Thanks.

**Comment by mrehder** [comment]
I can't share the full schemas.
This is the essential info.

          {
	 "$schema": "http://json-schema.org/draft-04/schema#",
	 "X": {
		 "type": "array",
		 "mergeStrategy": "arrayMergeById",
		 "mergeOptions": {
			 "idRef": "/Y"
		},
		 "items": {
			 "type": "object",
			 "anyOf": [
				{
					 "required": [
						"Y",
						"Z"
					]
				},
				{
					 "required": [
						"Y",
						"K"
					]
				}
			],
			 "properties": {
				 "Y": {
					 "type": "string"
				},
				 "Z": {
					 "type": "string"
				},
				 "K": {
					 "type": "string"
				}
			},
			 "additionalProperties": false
		},
		 "minItems": 1,
		 "uniqueItems": true
	}
}

**Comment by avian2** [comment]
I suspect you're just missing a `"mergeStrategy": "objectMerge"` at the same level as the `anyOf` keyword.

**Comment by mrehder** [comment]
What would it do at that level (under "type":"object" as a peer of "properties"?). This definition fragment defines no JSON content so it should be ignored in the merge. Basically "anyOf"/"oneOf" of "required" arrays should be skipped.

**Comment by mrehder** [comment]
Also if the strategy is declared as a peer of the anyOf within the object of an array items, this could override the "arraymergeById" strategy declared above for the array.

**Comment by avian2** [comment]
No, sorry. Given the sparse information you provided (no actual error message, no data and code to reproduce your problem apart from the partial schema), the best guess I can give you is in my previous comment. If you would like to learn more about why jsonmerge handles anyOf/allOf keywords the way it does, I invite you to browse the commit logs and search past issues (e.g. #29). I also suggest you read through jsonmerge's README file. I'm not going to discuss this further.

**Comment by mrehder** [comment]
I can't provide actual examples due to them being proprietary.

This is the traceback ( you didn't mention you needed that):
Traceback (most recent call last):
  File "/usr/bin/jsonmerge", line 38, in <module>
    main()
  File "/usr/bin/jsonmerge", line 32, in main
    result = jsonmerge.merge(result, json.load(file_handle), schema)
  File "/usr/lib/python2.7/site-packages/jsonmerge/__init__.py", line 372, in merge
    return merger.merge(base, head)
  File "/usr/lib/python2.7/site-packages/jsonmerge/__init__.py", line 330, in merge
    return walk.descend(schema, base, head).val
  File "/usr/lib/python2.7/site-packages/jsonmerge/__init__.py", line 85, in descend
    rv = self.work(strategy, schema, *args, **opts)
  File "/usr/lib/python2.7/site-packages/jsonmerge/__init__.py", line 126, in work
    rv = strategy.merge(self, base, head, schema, objclass_menu=self.merger.objclass_menu, **kwargs)
  File "/usr/lib/python2.7/site-packages/jsonmerge/strategies.py", line 307, in merge
    base[k] = walk.descend(subschema, base.get(k), v)
  File "/usr/lib/python2.7/site-packages/jsonmerge/__init__.py", line 85, in descend
    rv = self.work(strategy, schema, *args, **opts)
  File "/usr/lib/python2.7/site-packages/jsonmerge/__init__.py", line 126, in work
    rv = strategy.merge(self, base, head, schema, objclass_menu=self.merger.objclass_menu, **kwargs)
  File "/usr/lib/python2.7/site-packages/jsonmerge/strategies.py", line 217, in merge
    base.append(walk.descend(subschema, JSONValue(undef=True), head_item))
  File "/usr/lib/python2.7/site-packages/jsonmerge/__init__.py", line 59, in descend
    rv = self.call_descender(descender, schema, *args)
  File "/usr/lib/python2.7/site-packages/jsonmerge/__init__.py", line 109, in call_descender
    return descender.descend_instance(self, schema, base, head)
  File "/usr/lib/python2.7/site-packages/jsonmerge/descenders.py", line 124, in descend_instance
    return self.descend(schema)
  File "/usr/lib/python2.7/site-packages/jsonmerge/descenders.py", line 121, in descend
    raise SchemaError("Can't descend to 'allOf' and 'anyOf' keywords", schema)
jsonmerge.exceptions.SchemaError: 'arrayMergeById' merge strategy: Can't descend to 'allOf' and 'anyOf' keywords: #/properties/SubInterfaceDHCPConfigurations/items

Thanks
Mike
